### ISSUE TITLE
[Box plot] - Create sample JSON structure to showcase data that is to be part of box plot

### ISSUE THREAD

**Issue by rbadagandi1** [kruize/autotune#1032]
For each datapoint, It will have min, max, 25th percentile, 75th percentile and median
Short term - 5 dp (every 6 hours)
Med term - 8 dp (every day)
long term - 8 dp (every 2nd day)

**Comment by msvinaykumar** [comment]
tagged to https://github.com/kruize/autotune/pull/1089
