### ISSUE TITLE
[Bug] - Fix Jenkins pull request job when source code and test changes are in different branches 

### ISSUE THREAD

**Issue by shreyabiradar07** [kruize/autotune#1073]
The Jenkins job `kruize_test_pull_request`  functions correctly when source code and test changes are in the same branch. When tests are in a different branch from the source changes, the build does not pick up the test changes.

Jenkins build with source code - PR 944  and test branch `test_clusterName_listRecommendations` - PR 987  https://ci.app-svc-perf.corp.redhat.com/job/ExternalTeams/job/Autotune/job/kruize_test_pull_request/15/

**Comment by chandrams** [comment]
This is fixed now.  @shreyabiradar07 - You can close the issue after verification

**Comment by shreyabiradar07** [comment]
Closing this issue,
https://ci.app-svc-perf.corp.redhat.com/job/ExternalTeams/job/Autotune/job/kruize_test_pull_request/22/ - confirms the successful build with both source code and test changes
