### ISSUE TITLE
Exclude the additional 15 mins of data in plot since same datapoint is alloted for 2 sets of plot data

### ISSUE THREAD

**Issue by rbadagandi1** [kruize/autotune#1137]
As reported during validation of box plots, the plot data includes both the starting and ending time zones for the specified period. This results in the same data point being accounted for in two sets of plot data, leading to an additional 15 minutes of data in the plot. To address this issue, we should exclude the data from the monitoring start time when calculating the plot data.

**Comment by dinogun** [comment]
Fixed as part of #1189
