### ISSUE TITLE
Test scenarios for namespace level recommendations for kruize local

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#1277]
### Describe the feature 

Test scenarios for namespace level recommendations for kruize local

- Create an experiment with a valid namespace and datasource & generate recommendations. Validate the namespace recommendations json
- Create multiple exps with valid namespace and validate if recommendations are generated for all the exps
- Create multiple exps with diff clusters but same namespace & workloads and validate if recommendations are generated for all the exps
- Generate recommendations for each of the terms & validate it
- Generate recommendations when minimum no. of usage data points are available for each of the terms
- Configure Kruize with multiple data sources. Generate recommendations for experiments connected with different data sources
- Validate recommendations resource quota in the recommendations for
   - Pods, requests / limits for cpu & memory 

- Validate actual recommendations generated
  - Update validation infra to validate namespace level recommendations

 
- Create experiments with an invalid namespace and check for appropriate error messages
- Are there any new notifications specific to namespace level reco? Validate namespace recommendation notifications. For example,
- Generate recommendations when cpu usage metrics is zero or less than a millicore and validate notifications, ensure memory recommendations are generated
- Configure Kruize with multiple data sources. Bring down one of the data sources and generate recommendations for an experiment connected with a data source that is down and for another experiment connected to a datasource that is up
- Create an experiment with both containers & namespaces in the kubernetes object, what is the behavior?
- Create multiple exps with the same namespace, cluster & workload

**Comment by rbadagandi1** [comment]
Closing the issue since its PR #1293 is merged
