### ISSUE TITLE
Regex on Namespace

### ISSUE THREAD

**Issue by krishvoor** [kruize/autotune#1282]
### Describe the feature
The OCP cluster has many Namespace(s) starting with openshift-* [openshift-apiserver, openshift-console, openshift-etcd, openshift-ovn-kubernetes]. It would be essential from a user experience to have the ability to get recommendations for matching (based on regex) Namespace like this:

- Ending with openshift: `*-openshift`
- Starting with openshift: `openshift-*`
- Matching with openshift: `*-openshift-*`

### Suggest a solution
The above feature when translated should allow users to create an experiment like this:

```
[
    {
        "version": "v2.0",
        "experiment_name": "kube-apiserver-hc",
        "cluster_name": "default",
        "performance_profile": "resource-optimization-openshift",
        "mode": "monitor",
        "target_cluster": "local",
        "datasource": "prometheus-1",
        "kubernetes_objects": [
            {
                "type": "namespace",
                "name": "all-openshift-ns",
                "namespace": "openshift-*"
                ]
            }
        ],
        "trial_settings": {
            "measurement_duration": "15min"
        },
        "recommendation_settings": {
            "threshold": "0.1"
        }
    }
]
```

**Comment by dinogun** [comment]
@krishvoor The new bulk API being added into release 0.1 addresses this issue
