### ISSUE TITLE
dsmetadata api giving 400 error on UI 

### ISSUE THREAD

**Issue by bhanvimenghani** [kruize/autotune#1316]
**Describe the bug**
The api call` api/dsmetadata?datasource=prometheus-1&verbose=false` is responding with a 400 error code 

> {"message":"Metadata for a given datasource name - prometheus-1 either does not exist or is not valid","httpcode":400,"documentationLink":"","status":"ERROR"}

**How to reproduce it**
login the nerc cluster it has the latest kruize image 0.0.25 deployed with latest ui changes

**Expected behavior**
the api should function without 400 issue

**Relevant logs**
Attach any relevant logs to help debug the issue

**Environment:**
- Kubernetes Cluster : openshift 
- Version
- OS

**Additional context**
Add any other context about the problem here, any links or screenshots 
![Screenshot from 2024-10-03 18-28-11](https://github.com/user-attachments/assets/02bb4911-ad18-47da-8e55-485ca34ed42c)

**Comment by shreyabiradar07** [comment]
@bhanvimenghani can you please test the latest Kruize build - `quay.io/kruize/autotune_operator:0.1` and verify if the dsmetadata API 400 error is resolved on Kruize UI

**Comment by bhanvimenghani** [comment]
checked the ui with latest kruize image and ui image on nerc cluster and the issue is resolved.
