### ISSUE TITLE
 dsmetadata api has an issue with verbose set to true

### ISSUE THREAD

**Issue by bhanvimenghani** [kruize/autotune#1342]
**Describe the bug**
while calling the dsmetadata api on ui with verbose set to true either its not giving all the data or there is not enough data. 
**How to reproduce it**
check dsmetadata api on nerc cluster
http://kruize-ui-nginx-service-openshift-tuning.apps.nerc-ocp-test-2.nerc.mghpcc.org/api/dsmetadata?datasource=prometheus-1&cluster_name=default&verbose=true
this is the api call being made from the ui 
**Expected behavior**
UI expects to receive either complete data (nsp name, workload name , container details) or some notification if data is not available. 

**Environment:**
- nerc cluster

**Additional context**
![Screenshot from 2024-10-09 18-57-09](https://github.com/user-attachments/assets/a21ab1d5-4281-4332-80d7-108a797fe8f8)

**Comment by shreyabiradar07** [comment]
@bhanvimenghani can you please test the latest Kruize build - `quay.io/kruize/autotune_operator:0.1` and verify if the [dsmetadata?datasource=prometheus-1&cluster_name=default&verbose=true](http://kruize-ui-nginx-service-openshift-tuning.apps.nerc-ocp-test-2.nerc.mghpcc.org/api/dsmetadata?datasource=prometheus-1&cluster_name=default&verbose=true) API with verbose=true returns the container details.

**Comment by bhanvimenghani** [comment]
This is working fine, I can see workload and container details under each namespace with the latest build.
