### ISSUE TITLE
Structure of input search space to ML module from Recommendation Manager

### ISSUE THREAD

**Issue by agarwalrounak** [kruize/autotune#173]
The machine learning module expects an input json to get the `sla_class`, `direction`, `ml_algo`, `tunables`, etc. details.

Also, ref: https://github.com/kruize/autotune/issues/49

**Comment by ShishirH** [comment]
@agarwalrounak value_type should only be part of the tunables. 
```
    "objective_function": "transaction_response_time",
    "value_type": "double",
```
Is this an error?

Do you also require the sla_class?

**Comment by agarwalrounak** [comment]
If you look at the `recommended_config` [here](https://github.com/kruize/autotune/issues/172#issuecomment-781130363), `value_type` of the `objective_function` is part of the config. Thus, `value_type` of the `objective_function` is needed. 

`sla_class` is not required.
