### ISSUE TITLE
Python should not accept the experiment JSON with invalid/multiple url

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#230]
Python should not accept the experiment JSON with invalid/multiple url

**invalid-url**
```
{
"id" : "'${current_id}'",
 "url" : "http://localhost:8080/searchSpaces",
 "operation" : "EXP_TRIAL_GENERATE_NEW"
}
```
**multiple-url**
```
{
"id" : "'${current_id}'",
 "url" : "http://localhost:8080/searchSpace",
 "url" : "http://localhost:8080/searchSpace",
 "operation" : "EXP_TRIAL_GENERATE_NEW"
}
```

**Comment by agarwalrounak** [comment]
Some concerns about the 2 cases here:
- invalid-url
If the URL is always `http://localhost:8080/searchSpace`, maybe we shouldn't pass it at all. There is no point in the HPO performing a check if the value is fixed. If the HPO part already knows that the URL is supposed to be `http://localhost:8080/searchSpace`, it can straight away perform a GET on the URL when the `operation` is `EXP_TRIAL_GENERATE_NEW` or `EXP_TRIAL_GENERATE_SUBSEQUENT`.
- multiple-url
A JSON with duplicate keys isn't invalid by definition. If we were to access the value of a key which has duplicates, the value of the last duplicate key would be returned. So, a JSON schema check won't be able to detect duplicate keys. 
Will add a separate check for this.

@dinogun @chandrams

**Comment by chandrams** [comment]
@agarwalrounak 

invalid url -  If we make HPO as a standalone module in future then we will need to validate the URL being passed

multiple url - Yes, I agree that this isn't an invalid case. Will check and fix the test if it is marked as invalid.

**Comment by agarwalrounak** [comment]
invalid url - I can add an if condition to validate the URL passed. My point here is if HPO is validating the URL passed then it already knows the URL value. What if the URL value changes? How will HPO be made aware of it? If HPO already knows the correct value of the URL, can't it straight away perform a GET on the URL when the `operation` is `EXP_TRIAL_GENERATE_NEW` or `EXP_TRIAL_GENERATE_SUBSEQUENT`.

multiple url - A good point to discuss here is what should be our stance for multiple url or in general for duplicate keys. Should we mark them as invalid by adding appropriate checks or let them be? 
If we want to mark them as invalid, I can add a separate check to detect duplicate keys.

**Comment by dinogun** [comment]
The URL is actually not fixed, ideally we do not want the python code to be aware of any inner working of the calling module. It is better that we send you the full URL, which you can verify if it is valid by checking you get a `200 OK`. You don't need to do any other static checks.
