### ISSUE TITLE
Algebraic Expression Parser for the Analyzer Module

### ISSUE THREAD

**Issue by dinogun** [kruize/autotune#293]
Need to have a full fledged algebraic expression parser that can handle complex algebraic expressions for specifying the performance objective.

Algebraic Expressions can be of type `a/b` such as in [this](https://github.com/kruize/benchmarks/blob/master/techempower/autotune/autotune-http_resp_time.yaml#L8) example or a more complex one such as `(a^2)/(b/2)*sqrt(c))`.

**Comment by bharathappali** [comment]
@dinogun Thanks for adding an issue to address the need for an Algebraic Expression Parser.

To have a clear picture of the issue, I came up with a set of assumptions which I got after going through the issue description. Please correct me if I'm wrong

- As the title mentions `for the Analyser Module` I expect the implementation should be in `Java`
- I'm expecting the end goal of this expression parser is to come up with a dynamically calculated result based on the function variables listed in yaml and the expression given in the yaml

**Comment by ShishirH** [comment]
@bharathappali Can I pick this up?

**Comment by chandrams** [comment]
@ShishirH - Bharath isn't working on this one, so go ahead. Thanks.

**Comment by khansaad** [comment]
@dinogun I found this open source project which is licensed under the MIT Open Source license. It seems to be doing pretty much what are requirements are. 

https://github.com/uklimaschewski/EvalEx

**Comment by prahaladhchandrahasan** [comment]
Is this issue still open if yes, then I would like to work on it

**Comment by dinogun** [comment]
Closing this as this is now available through the PR #366
