### ISSUE TITLE
Update README.md in autotune/scripts

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#32]
Update the README:

- Remove details regarding prometheus installation from output of deploy.sh as we have moved prometheus installation to a separate script
- Include a pre-requisites section and provide details of pre-requisites required and steps to run prometheus_on_minikube.sh
- Remove/Update the reference to dashboard in the readme -  https://github.com/kruize/autotune/blob/master/grafana/autotune_kubernetes_dashboard.json 
- Link to Add Application Label in the below text in readme doesn't exist.
Note: autotune only monitors application with a specific label. See Add Application Label below for more info.

**Comment by dinogun** [comment]
Can this be closed now ?

**Comment by chandrams** [comment]
Closing this as all issues reported here are now fixed.
