### ISSUE TITLE
Enquiry on mission parity with godon project

### ISSUE THREAD

**Issue by cherusk** [kruize/autotune#412]
I'm working on a project inherently similar to autotune[1]. Apart from k8s deployed technologies, I'm targeting any format of deployment.
So could be also a traditional stack or something that simply cannot be deployed via k8s but can benefit from optimization. Could be a network device, could be a traditional linux stack.

k8s as orchestration engine for the actual optimizer instances I'm also thinking to implement, along others, like celery alone.

Hence the only parity gap I can see is that this project is not planning to target any deployment format other than k8s. But from your architecture, basing on prometheus metrics, you also could target any format of deployment outside of k8s. So autotune running and doing its optimization processing within k8s, but applying changes or suggesting "golden configurations" outside of k8s.

Is this something that you're planning for the future? It would help me to decide on the future of godon project.

Thanks and kind regards.

[1] https://github.com/cherusk/godon

**Comment by dinogun** [comment]
@cherusk Thank you for reaching out! I took a quick look at the godon (deep meaning!) project and I have a few thoughts on what you have mentioned above.

1. Autotune's primary focus is going to be Kubernetes as we are trying to automate all aspects of arriving at a optimal configuration.
2. That said, we are planning to look into usecases beyond kubernetes, eg optimizing the microservice build process on a developer laptop (no kubernetes), optimizing applications running outside Kubernetes etc.
3.  More recently we are looking into optimizing the OS in conjunction with the [TuneD](https://github.com/redhat-performance/tuned) and [Node Tuning Operator](https://github.com/openshift/cluster-node-tuning-operator) projects.
4. For many of the non-kubernetes usecases, IMO, the primary requirement is to have a hyper parameter optimization (HPO) framework that can provide easy access to tunable configurations that can be experimented with. To this end, we are standardizing the HPO APIs and are running it as a service that is currently packaged with Autotune but can be independently accessed as well. You can think of this as "HPO as a Service". This means that one can add scaffolding around it to match it to a specific usecase. Hopefully that usecase can then be fully integrated into Autotune itself.

If you are interested, you can join our [slack](https://join.slack.com/t/kruizeworkspace/shared_invite/zt-nmxjz4n6-xX1FiCUljciMzltcItDI~w) and I can describe these in a little bit more detail. You can present about godon in our community call and we can discuss ways that we can work jointly. Looking forward to hear from you!

**Comment by cherusk** [comment]
@dinogun 

thanks for your comprehensive reaction. Much clearer to me. So I understand your overall objective is certainly to reach beyond k8s.

> If you are interested, you can join our [...]

Certainly interested, highly appreciating that invitation, coming.

Closing this issue as communication platform hence.
