### ISSUE TITLE
Timestamp validation required in Update Results API 

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#558]
Timestamp validation is required in Update Results API. For example, specifying same start & end timestamps works fine.

**Comment by chandrams** [comment]
@khansaad - Timestamp validation for invalid/blank/NULL is this done as part of this fix, I still see those failing. Will it be fixed in issue #561

**Comment by khansaad** [comment]
Yes. It will be covered under #561

**Comment by khansaad** [comment]
Fixed as part of #1057
