### ISSUE TITLE
Validate blank/null/invalid values for keys in updateResults json

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#561]
Validate blank/null/invalid values for keys in updateResults json and return appropriate error messages 

For example, updateResults API returns 201 on passing blank or invalid values to memoryRSS units or memoryRSS max

**Comment by rbadagandi1** [comment]
@khansaad  to raise a different PR for test case execution and assign it to @chandrams for verification. Post which this issue can be closed.

**Comment by rbadagandi1** [comment]
Merged for 20.2 release for PR 1057
