### ISSUE TITLE
Add cluster name field in Create Experiment API and Update result API

### ISSUE THREAD

**Issue by bharathappali** [kruize/autotune#566]
The current JSON/YAML sent to the autotune is not having the field `cluster_name`, This field can be much useful when autotune is set to work in a environment which involves multiple clusters. Currently this field can be optional and not required while creating experiments

Changes expected:
- [Kruize Object](https://github.com/kruize/autotune/pull/565) needs to have a field to store cluster name
- Doc changes
- CRD changes
- Test changes

**Comment by dinogun** [comment]
This is now available in the 0.0.8_mvp image
