### ISSUE TITLE
CORS header

### ISSUE THREAD

**Issue by msvinaykumar** [kruize/autotune#640]
add CORS headers at the top level by using Filter. Filters allow you to modify requests and responses as they pass through the server. Here's how you can add CORS headers using a filter:

`public class CorsFilter implements Filter {

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {}

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
            throws IOException, ServletException {
        HttpServletResponse httpResponse = (HttpServletResponse) response;

        // Set CORS headers
        httpResponse.setHeader("Access-Control-Allow-Origin", "*");
        httpResponse.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
        httpResponse.setHeader("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");

        chain.doFilter(request, response);
    }

    @Override
    public void destroy() {}
}`

Register the CorsFilter in your Jetty server

`  Server server = new Server(8080);

        ServletContextHandler contextHandler = new ServletContextHandler(ServletContextHandler.SESSIONS);
        contextHandler.setContextPath("/");

        // Register the CorsFilter
        contextHandler.addFilter(CorsFilter.class, "/*", null);`
        
        
by this we can avoid adding cores to each servlet. 
 Utils.addCORSHeaders(response);

**Comment by bharathappali** [comment]
> by this we can avoid adding cores to each servlet.
 Utils.addCORSHeaders(response);

Thanks @msvinaykumar for raising this issue. This was added as [TODO](https://github.com/kruize/autotune/blob/mvp_demo/src/main/java/com/autotune/utils/Utils.java#L149) to make changes in future after finalising the scope of API's as some API's can be internal ones which are not to be exposed to be accessed from a different domain (Currently I expect we don't have any). If the contributors are comfortable to proceed implementing this I can add it to my tasks for this release cycle. 

FYI @dinogun

**Comment by dinogun** [comment]
Complete as per #644
