### ISSUE TITLE
[Test] Evaluate time taken to run 5k experiment_results for every experiment to make listRecomm API available

### ISSUE THREAD

**Issue by rbadagandi** [kruize/autotune#647]
This evaluation is to validate the time taken to run 5k experiment_results for every single experiment (Assuming a total of 100 experiments) and test how long it takes to get listRecommendation API to be made available for consumption

**Comment by chandrams** [comment]
Scalability test results
Experiments = 10000
Days of metric results data uploaded = 15 days (14461671 results)
CPU (Avg/Max)   - 25.24/45.63 cores
CPU (Req/Limit) - 4 cores/None
Mem (Avg/Max)   - 6.91/7.48 Gi
Mem (Req/Limit) - 4/8 Gi
DB size         - 76 GB
Execution Time  - 10.5 Days
