### ISSUE TITLE
[Database] Implement UUID and build common interface for single upload and bulk upload

### ISSUE THREAD

**Issue by rbadagandi** [kruize/autotune#677]
This requires a new API with UUID which ROS will use to get UUID results (status of each request and its status success or not)

**Singular upload - 1 experiment 1 request sent and retreiving the status (success or failure)
**Bulk - multiple experiments - 1 request with status with reasoning of failure
** UUID is applicable per request sent by ROS (irrespective of no of experiments)

**Comment by msvinaykumar** [comment]
There's no requirement to incorporate UUID for ROS, given that inserting 100 rows of data takes less than a second.
we can close this issue
