### ISSUE TITLE
Investigate the error message seen in listRecommendations json

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#680]
1) I see the below error message in the listRecommendations json:

```
"medium_term": {
                      "monitoring_start_time": "2023-03-29T08:17:59.196Z",
                      "monitoring_end_time": "2023-04-05T08:17:59.196Z",
                      "duration_in_hours": 17.0,
                      "pods_count": 0,
                      "confidence_level": 0.0,
                      "config": {
                        "requests": {
                          "cpu": {
                            "amount": 0.0,
                            "errorMsg": "Cannot invoke \"com.autotune.common.data.metrics.MetricAggregationInfoResults.getSum()\" because the return value of \"java.util.HashMap.get(Object)\" is null"
                          },
                          "memory": {
                            "amount": 859.1034526209679,
                            "format": "MiB"
                          }
                        },
                        "limits": {
                          "cpu": {
                            "amount": 0.0,
                            "errorMsg": "Cannot invoke \"com.autotune.common.data.metrics.MetricAggregationInfoResults.getMax()\" because the return value of \"java.util.HashMap.get(Object)\" is null"
                          },
                          "memory": {
                            "amount": 2170.7343750000073,
                            "format": "MiB"
                          }
                        }
                      },
```

To recreate this issue, the test can be run below test can be run by following the steps in this [doc](https://github.com/kruize/autotune/blob/mvp_demo/tests/scripts/remote_monitoring_tests/Remote_monitoring_tests.md) on how to run the test without using test_autotune.sh
```
pytest -s test_list_recommendations.py::test_list_recommendations_multiple_exps_with_missing_metrics
```

2) Scale tests too failed with 0 values for cpu requests and limits in the recommendations and also format is missing for cpu in the listRecommendations output

These messages are displayed in the kruize pod log, looks similar to the issue reported here.
[kruize_pod.log](https://github.com/kruize/autotune/files/11090029/kruize_pod.log)

**Comment by khansaad** [comment]
@chandrams 
After making changes in #637 , I'm not seeing this error. Can you verify with this image once `khansaad/autotune_operator:container-test` ?

**Comment by kusumachalasani** [comment]
Because of this error, cpuRequests also shows as zero even though cpuUsage is greater than zero.
This error happens when cpuThrottle_sum is empty.

**Comment by chandrams** [comment]
Verified the issues reported here these are fixed now. 

@kusumachalasani - Can you verify this as well.

**Comment by kusumachalasani** [comment]
The data comes up as expected now.
