### ISSUE TITLE
Investigate the high cpu usage shown for kruize in the stress test

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#683]
Cpu usage of kruize seems to be high when the stress test is run. Need to check if there are issues with the way resource usage is captured or the kruize cpu usage is indeed high

To run the test:

- Clone the github kruize repo
- cd tests/scripts/remote_monitoring_tests/stress_test
- To run the test (by default it runs with 1000 users, can be increased by using the cmdline options) :
    - ./remote_monitoring_stress_test.sh -c minikube -r /tmp/stress-test-results -i kruize/autotune_operator:0.0.11_mvp (minikube)
    - ./remote_monitoring_stress_test.sh -c openshift -r /tmp/stress-test-results -i kruize/autotune_operator:0.0.11_mvp (openshift)

**Comment by chandrams** [comment]
[results.zip](https://github.com/kruize/autotune/files/11086856/results.zip)

**Comment by msvinaykumar** [comment]
we can use a Java profiler like VisualVM or JProfiler to analyze CPU usage.this tools tell us which parts of our code are consuming more CPU cycles and help to identify performance bottlenecks. 

@chandrams Any idea what was the previous calculation , I remember you mentioned more memory but less cpu.

**Comment by msvinaykumar** [comment]
@chandrams Could you please confirm if the CPU usage decreases after stress testing? I am wondering if the CPU usage is being utilized unnecessarily. Also, do you happen to know the approximate duration for which both the CPU and memory are being used?

**Comment by chandrams** [comment]
This issue is no longer valid, wiil raise a new issue if required
