### ISSUE TITLE
[Database] Environment variable should took precedence over configuration file.

### ISSUE THREAD

**Issue by patilsuraj767** [kruize/autotune#685]
Here - https://github.com/kruize/autotune/blob/master/src/main/java/com/autotune/database/init/KruizeHibernateUtil.java#L42-L62 I can see kruize first checks for configuration file and if file not found then looks for the env variable.
Request is to first get database config from configuration files and then override the config if any database environment variable is set.

**Comment by dinogun** [comment]
@patilsuraj767 The configuration file that is being referenced is actually this configmap [JSON](https://github.com/kruize/autotune/blob/master/manifests/crc/default-db-included-installation/openshift/kruize-crc-openshift.yaml#L71) mounted on a shared volume and is part of the manifest file. Does this not meet your requirement?

**Comment by patilsuraj767** [comment]
I have reviewed and tested the changes in local setup but it is not working as expected. 
When I pass all the DB config as environment variable only then variables are getting override, but requirement was that service should read all other DB configs(username, password. hostname and port) from config file and only the DB name should be read from environment variable. 
Also can we change the environment variable names? maybe we can prefix them with `db_`. Current environment variable names are too generic. 
```
      - name=autotune
      - hostname=db-ros
      - username=postgres
      - password=postgres
      - port=5432
```

**Comment by patilsuraj767** [comment]
Thanks @msvinaykumar, Once 0.0.13_rm is available I will try to upgrade to it in ROS-OCP.

**Comment by msvinaykumar** [comment]
This is working as expected and ready to close.
