### ISSUE TITLE
[Bug] Kruize changes interval_start timestamp in listRecommendation API.

### ISSUE THREAD

**Issue by patilsuraj767** [kruize/autotune#696]
Version - 0.0.11_rm
Branch - remote_monitoring

When I summit the payload with certain start_timestamp via update_result API and then it is expected that listRecommendation API should output the same start_timestamp. 
Current behavior which I have observed is when we summit start_timestamp as `"start_timestamp":"2023-03-30T00:00:01.000Z"` via update_result than with listRecommendation API I get `"monitoring_start_time": "2023-03-29T00:15:00.000Z"`.  It seems kruize is always decrementing date by `1 day` and set time to `15:00.000Z`.

**Comment by dinogun** [comment]
Hi Suraj, this is actually as designed. The `monitoring_start_time` to`monitoring_end_time` window corresponds to the size of the observation period being considered for the specific duration term ie `1 day` for `short_term`, `7 days` for `medium_term` and `15 days` for `long term`. The `monitoring_end_time` however will always coincide with the `end_timestamp` in `updateResults` and is used as the `key` in the `recommendations` object of the JSON. I hope that clarifies.

**Comment by patilsuraj767** [comment]
Hello @dinogun, Thanks for the clarification, Understood your point. 
I think we can close this bug.
