### ISSUE TITLE
[Notifications] Kruize to implement a numbered code for notification

### ISSUE THREAD

**Issue by rbadagandi** [kruize/autotune#733]

**Comment by chandrams** [comment]
Verified the [notification codes](https://github.com/kruize/autotune/blob/mvp_demo/design/NotificationCodes.md) except the below with 0.0.15_mvp build:

CPU_RECORDS_NOT_AVAILABLE
MEMORY_RECORDS_ARE_ZERO
MEMORY_RECORDS_NOT_AVAILABLE
