### ISSUE TITLE
Scale test failed with OOM thread in C3P0PooledConnectionPoolManager

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#781]
Scale test (#766) failed after 204 exps / 1500 results posted with OOM on both minikube and openshift with kruize/autotune_operator:0.0.13_rm

```
Waiting for experiments ...
2023-04-2316:29:58.695 INFO [qtp28094269-37][PerformanceProfileUtil.java(140)]-Added PerformanceProfile: resource-optimization-openshift
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "C3P0PooledConnectionPoolManager[identityToken->2wzy8jav1cjephy10w4bfn|7ca0863b]-AdminTaskTimer"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Connector-Scheduler-20f5281c-1"

```

On minikube:
Limits:
memory: 4Gi
Requests:
cpu: 4
memory: 4Gi

On Openshift (quicklab):
Limits:
memory: 4Gi
Requests:
cpu: 3 ==> reduced it to 3 as the worker nodes had only 4 cores
memory: 4Gi

**Comment by msvinaykumar** [comment]
@chandrams this seems no more valid can we close this issue ?

**Comment by chandrams** [comment]
This issue has been fixed
