### ISSUE TITLE
Recommendation of 0.0 should not be sent if current req/limit is 0.1

### ISSUE THREAD

**Issue by rbadagandi** [kruize/autotune#810]
"metrics": [
                                        {
                                            "name": "cpuRequest",
                                            "results": {
                                                "aggregation_info": {
                                                    "sum": 0.1,
                                                    "avg": 0,
                                                    "format": "cores"
                                                }
                                            }
                                        },
                                        {
                                            "name": "cpuLimit",
                                            "results": {
                                                "aggregation_info": {
                                                    "sum": 0.1,
                                                    "avg": 0,
                                                    "format": "cores"
                                                }
                                            }
                                        },
                                        {
                                            "name": "cpuUsage",
                                            "results": {
                                                "aggregation_info": {
                                                    "min": 0,
                                                    "max": 0,
                                                    "sum": 0,
                                                    "avg": 0,
                                                    "format": "cores"
                                                }
                                            }
                                        },
                                        {
                                            "name": "cpuThrottle",
                                            "results": {
                                                "aggregation_info": {
                                                    "sum": 0,
                                                    "max": 0,
                                                    "avg": 0,
                                                    "format": "cores"
                                                }
                                            }
                                        },

With the above input, Kruize should not recommend CPU requests to set 0.0 instead of current 0.1. Minimum recommendation should be something you can set in OCP and still have the workload running 
![image](https://user-images.githubusercontent.com/89081154/236855482-53a8cc3e-8148-40ce-bf62-92245ef5fbec.png)

**Comment by chandrams** [comment]
Verified this with zero cpu usage and low cpu usage results shared by @bharathappali on 0.0.15_mvp and verified these notification codes are displayed


323001 | NOTICE | CPU_RECORDS_ARE_IDLE | Specifies that the CPU records in the observed period are less than a millicore | CPU Usage is less than a millicore, No CPU Recommendation can be generated | DATA USER
-- | -- | -- | -- | -- | --
323002 | NOTICE | CPU_RECORDS_ARE_ZERO | Specifies that the CPU recordings are ZERO | CPU usage is zero, No CPU Recommendations can be generated | DATA USER
