### ISSUE TITLE
[UI] Redirect to Kruize service instead of hardcoding port number

### ISSUE THREAD

**Issue by rbadagandi** [kruize/autotune#824]
Kruize and Kruize UI should run together in minikube - we have servicename 'kruize' fixed,in manifest CRC default yaml - except namespace everything remain same
Kind: service 
If kruize restarts, IP address will change hence it is preferred to use service name instead of port number hardcoded

**Comment by bhanvimenghani** [comment]
@rbadagandi this task is also completed

**Comment by rbadagandi1** [comment]
Closing this issue since this is delivered as part of V0.0.18
