### ISSUE TITLE
Move PR checks to use a test docker image with a PR signature

### ISSUE THREAD

**Issue by dinogun** [kruize/autotune#849]
Test infra and git workflows for both PR check and merge should create docker images with a PR signature to ensure that there are no name clashes from multiple PRs

Current git workflows use `:test` which can clash when multiple PRs are pushed / merged at the same time.

**Comment by dinogun** [comment]
@chandrams Do you have any update on this?

**Comment by chandrams** [comment]
@dino - Sorry, forgot to link the pull request  - https://github.com/kruize/autotune/pull/856

**Comment by chandrams** [comment]
PR is merged, closing this issue
