### ISSUE TITLE
kruize scalability tests are failing with connection errors

### ISSUE THREAD

**Issue by chandrams** [kruize/autotune#865]
Scalability test failed with the below issue on openshift:

```
An error occurred while connecting to HTTPConnectionPool(host='<host addr>', port=80): Max retries exceeded with url: /createPerformanceProfile (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8c6f1aae80>: Failed to establish a new connection: [Errno 99] Cannot assign requested address',))
### Experiment: scaleexp_2: Progress: 2/100  86/96
An error occurred while connecting to HTTPConnectionPool(host='host addr', port=80): Max retries exceeded with url: /createPerformanceProfile (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8c6f183ef0>: Failed to establish a new connection: [Errno 99] Cannot assign requested address',))
### Experiment: scaleexp_2: Progress: 2/100  87/96
```

To recreate the issue:

- git clone the tests from https://github.com/kruize/autotune/pull/832
- cd autotune/tests/scripts/remote_monitoring_tests/scale_test
- ./remote_monitoring_scale_test.sh -c openshift  -i chandra25ms/autotune_operator:pr859   -u 10000 -d 2 -t 40000 -r /tmp/results-scale-test-openshift

**Comment by msvinaykumar** [comment]
@chandrams Can you please confirm if this is still correct ?

**Comment by chandrams** [comment]
@msvinaykumar - Yes seen on scalelab but with the scalability test changes in PR 832, have you added your scalability test changes on top of it? I will test it again on scalelab.

**Comment by msvinaykumar** [comment]
@chandrams yes added scalability scripts

you can run like this to create experiments for 15 days 5k experiments 

for i in {1..20}; do nohup `time ./bulkScalabilityWrapper.sh --ip kruize-openshift-tuning.apps.kruiz.dsal.lab.eng.tlv2.redhat.com --port 0 --count 250,24 --minutesjump 15 --initialstartdate 2023-01-01T00:00:00.000Z --name test100k15daysT1-${i} --limitdays 15 --intervalhours 6 >> /tmp/test100k15daysT1-${i}.log 2>&1` & done ;

**Comment by chandrams** [comment]
This issue is no longer seen with the updated scripts, tested on scalelab cluster
