### ISSUE TITLE
[UI] - Fix proxy issue to release UI V0.0.1

### ISSUE THREAD

**Issue by rbadagandi1** [kruize/autotune#885]
This issue is to track server side rendering issue of mapping ROS Backend APIs with Kruize UI

Packaging and deployment of Kruize UI

**Comment by bhanvimenghani** [comment]
@rbadagandi1 This issue is resolved and can be closed

**Comment by rbadagandi1** [comment]
Marking this as closed since this was delivered as part of V0.0.18
