### ISSUE TITLE
[DB Scalability] Java changes corresponding to the DB partition, DDL changes and Cron jobs

### ISSUE THREAD

**Issue by khansaad** [kruize/autotune#929]
Java related changes needed for the DB Scalability updates:

1. Add Request and limit to Postgres
2. Java changes for the DDL SQL file
3. Add DB partitions changes
4. Create Kubernetes Cron jobs to do the retention

**Comment by rbadagandi1** [comment]
4. Create Kubernetes Cron jobs to do the retention is pending and did not go as part of V0.0.19 release. There will be a separate PR created to include this change.
Rest of the changes completed as part of V0.0.19 hence closing.
