### ISSUE TITLE
Suppress duplicate Key value error message

### ISSUE THREAD

**Issue by rbadagandi1** [kruize/autotune#998]
Timestamp already exists errors - [Detail: Key (experiment_name, interval_end_time, interval_start_time)=(11787264|345199|683cb481-8f8f-4948-9173-29f730c5c03f|btr-spm-solution-prod|deployment|app-s2m-prd, 2023-10-11 00:30:00, 2023-10-11 00:15:01) already exists. 2023-10-1815:07:41.847 ERROR [qtp88397182-34][SqlExceptionHelper.java(138)]-ERROR: duplicate key value violates unique constraint "kruize_results_20231011_pkey" - This is due to the new cost operator that now sends aggregated records through out the day for customer that have enabled it.

For the last 6 hr period of the day, Kruize will have to reject 75% of the records as these would already have been added. Kruize will for now suppress printing the “duplicate key value” error message.

**Comment by rbadagandi1** [comment]
Completed as part of PR #1004

**Comment by msvinaykumar** [comment]
Seems we not resolved this issue @khansaad please confirm .


It appears that we're unable to resolve this problem since the message is being generated by a third-party Java package, making it challenging to manage the logging messages.

**Comment by rbadagandi1** [comment]
This issue is partially fixed as part of PR #1004 

We're unable to suppress the duplicate record error coming from the SQLExceptionHelper class. This needs to be handled at log4j properties file
